"""adding user relation mixin in tables

Revision ID: 05213771cae6
Revises: 18e8ac7f126d
Create Date: 2023-11-26 12:10:59.798941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05213771cae6'
down_revision: Union[str, None] = '18e8ac7f126d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
